#erver.port=8762
#spring.application.name=xcloud-test
#eureka
#eureka.client.registerWithEureka=true
#eureka.instance.preferIpAddress=true
#eureka.client.service-url.defaultZone=http://localhost:8760/eureka/
#datasource
#spring.datasource.url=jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8
#spring.datasource.username=root
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver
#MyBatis
#mybatis.type-aliases-package=com.xcloud.framework.entity
#mybatis.mapper-locations=classpath:mapper/*.xml
#mybatis-plus
#mybatis-plus.mapper-locations=classpath*:mybatis/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8760/eureka/
server:
  port: 8762
spring:
  application:
    name: xcloud-test



security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8710/oauth/current
    client:
      id: client_2
      client-secret: 123456
      access-token-uri: http://localhost:8710/oauth/token
      grant-type: client_credentials,password
      scope: server
